/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.Jogo;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Adelino Neto
 */
public class JanelaMultiplayerCliente extends javax.swing.JFrame {
    Jogo jogo;
    
    Socket socketCliente;
    BufferedReader entradaServidor;
    DataOutputStream saidaServidor; 

    /**
     * Creates new form TelaMultiplayerCliente
     */
    public JanelaMultiplayerCliente() {
        initComponents();
        jogo = new Jogo(false);
        renomearBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jB_0_0 = new javax.swing.JButton();
        jB_0_1 = new javax.swing.JButton();
        jB_0_2 = new javax.swing.JButton();
        jB_0_3 = new javax.swing.JButton();
        jB_0_4 = new javax.swing.JButton();
        jB_1_0 = new javax.swing.JButton();
        jB_1_1 = new javax.swing.JButton();
        jB_1_2 = new javax.swing.JButton();
        jB_1_3 = new javax.swing.JButton();
        jB_1_4 = new javax.swing.JButton();
        jB_2_0 = new javax.swing.JButton();
        jB_2_1 = new javax.swing.JButton();
        jB_2_2 = new javax.swing.JButton();
        jB_2_3 = new javax.swing.JButton();
        jB_2_4 = new javax.swing.JButton();
        jTextIP = new javax.swing.JTextField();
        jB_Conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gif1.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jB_0_0.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_0ActionPerformed(evt);
            }
        });

        jB_0_1.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_1ActionPerformed(evt);
            }
        });

        jB_0_2.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_2ActionPerformed(evt);
            }
        });

        jB_0_3.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_3ActionPerformed(evt);
            }
        });

        jB_0_4.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_4ActionPerformed(evt);
            }
        });

        jB_1_0.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_0ActionPerformed(evt);
            }
        });

        jB_1_1.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_1ActionPerformed(evt);
            }
        });

        jB_1_2.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_2ActionPerformed(evt);
            }
        });

        jB_1_3.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_3ActionPerformed(evt);
            }
        });

        jB_1_4.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_4ActionPerformed(evt);
            }
        });

        jB_2_0.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_0ActionPerformed(evt);
            }
        });

        jB_2_1.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_1ActionPerformed(evt);
            }
        });

        jB_2_2.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_2ActionPerformed(evt);
            }
        });

        jB_2_3.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_3ActionPerformed(evt);
            }
        });

        jB_2_4.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_4ActionPerformed(evt);
            }
        });

        jTextIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIPActionPerformed(evt);
            }
        });

        jB_Conectar.setText("Conectar");
        jB_Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jB_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jB_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jB_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Conectar)
                            .addComponent(jTextIP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Conectar)
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean testarJogada(javax.swing.JButton botao){
        String[] array = botao.getName().split("_");
        String nome = array[0]+"_"+array[1]+"_"+array[2];
        int x = Integer.parseInt(array[1]);
        int y = Integer.parseInt(array[2]);
        boolean result = jogo.iniciar(x, y);
        if(result == false){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gif2.gif")));
            botao.setText("X");
            JOptionPane.showMessageDialog(null,"YOU LOSE!");
            return false;
        }
        return true;
    }
    
    private void disableAllButtons() {
        jB_0_0.setEnabled(false);
        jB_0_1.setEnabled(false);
        jB_0_2.setEnabled(false);
        jB_0_3.setEnabled(false);
        jB_0_4.setEnabled(false);
        jB_1_0.setEnabled(false);
        jB_1_1.setEnabled(false);
        jB_1_2.setEnabled(false);
        jB_1_3.setEnabled(false);
        jB_1_4.setEnabled(false);
        jB_2_0.setEnabled(false);
        jB_2_1.setEnabled(false);
        jB_2_2.setEnabled(false);
        jB_2_3.setEnabled(false);
        jB_2_4.setEnabled(false);
    }
    
        private void renomearBotoes() {
        jB_0_0.setName("jB_0_0");
        jB_0_1.setName("jB_0_1");
        jB_0_2.setName("jB_0_2");
        jB_0_3.setName("jB_0_3");
        jB_0_4.setName("jB_0_4");
        jB_1_0.setName("jB_1_0");
        jB_1_1.setName("jB_1_1");
        jB_1_2.setName("jB_1_2");
        jB_1_3.setName("jB_1_3");
        jB_1_4.setName("jB_1_4");
        jB_2_0.setName("jB_2_0");
        jB_2_1.setName("jB_2_1");
        jB_2_2.setName("jB_2_2");
        jB_2_3.setName("jB_2_3");
        jB_2_4.setName("jB_2_4");
    }
    
    public void habilitaTabuleiro(){
        if(jB_0_0.getName() != "false")
        jB_0_0.setEnabled(true);
        if(jB_0_1.getName() != "false")
        jB_0_1.setEnabled(true);
        if(jB_0_2.getName() != "false")
        jB_0_2.setEnabled(true);
        if(jB_0_3.getName() != "false")
        jB_0_3.setEnabled(true);
        if(jB_0_4.getName() != "false")
        jB_0_4.setEnabled(true);
        if(jB_1_0.getName() != "false")
        jB_1_0.setEnabled(true);
        if(jB_1_1.getName() != "false")
        jB_1_1.setEnabled(true);
        if(jB_1_2.getName() != "false")
        jB_1_2.setEnabled(true);
        if(jB_1_3.getName() != "false")
        jB_1_3.setEnabled(true);
        if(jB_1_4.getName() != "false")
        jB_1_4.setEnabled(true);
        if(jB_2_0.getName() != "false")
        jB_2_0.setEnabled(true);
        if(jB_2_1.getName() != "false")
        jB_2_1.setEnabled(true);
        if(jB_2_2.getName() != "false")
        jB_2_2.setEnabled(true);
        if(jB_2_3.getName() != "false")
        jB_2_3.setEnabled(true);
        if(jB_2_4.getName() != "false")
        jB_2_4.setEnabled(true);
    }
        
    private void jB_0_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_0ActionPerformed
        disableAllButtons();
        jB_0_0.setBackground(Color.black);
        String[] array = jB_0_0.getName().split("_");
        if(testarJogada(jB_0_0) == false){
            this.jB_0_0.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_0_0.setName("false");
    }//GEN-LAST:event_jB_0_0ActionPerformed

    private void jB_0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_1ActionPerformed
        disableAllButtons();
        jB_0_1.setBackground(Color.black);
        String[] array = jB_0_1.getName().split("_");
        if(testarJogada(jB_0_1) == false){
            this.jB_0_1.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_0_1.setName("false");
    }//GEN-LAST:event_jB_0_1ActionPerformed

    private void jB_0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_2ActionPerformed
        disableAllButtons();
        jB_0_2.setBackground(Color.black);
        String[] array = jB_0_2.getName().split("_");
        if(testarJogada(jB_0_2) == false){
            this.jB_0_2.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_0_2.setName("false");
    }//GEN-LAST:event_jB_0_2ActionPerformed

    private void jB_0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_3ActionPerformed
        disableAllButtons();
        jB_0_3.setBackground(Color.black);
        String[] array = jB_0_3.getName().split("_");
        if(testarJogada(jB_0_3) == false){
            this.jB_0_3.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_0_3.setName("false");
    }//GEN-LAST:event_jB_0_3ActionPerformed

    private void jB_0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_4ActionPerformed
        disableAllButtons();
        jB_0_4.setBackground(Color.black);
        String[] array = jB_0_4.getName().split("_");
        if(testarJogada(jB_0_4) == false){
            this.jB_0_4.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_0_4.setName("false");
    }//GEN-LAST:event_jB_0_4ActionPerformed

    private void jB_1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_0ActionPerformed
        disableAllButtons();
        jB_1_0.setBackground(Color.black);
        String[] array = jB_1_0.getName().split("_");
        if(testarJogada(jB_1_0) == false){
            this.jB_1_0.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_1_0.setName("false");
    }//GEN-LAST:event_jB_1_0ActionPerformed

    private void jB_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_1ActionPerformed
        disableAllButtons();
        jB_1_1.setBackground(Color.black);
        String[] array = jB_1_1.getName().split("_");
        if(testarJogada(jB_1_1) == false){
            this.jB_1_1.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_1_1.setName("false");
    }//GEN-LAST:event_jB_1_1ActionPerformed

    private void jB_1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_2ActionPerformed
        disableAllButtons();
        jB_1_2.setBackground(Color.black);
        String[] array = jB_1_2.getName().split("_");
        if(testarJogada(jB_1_2) == false){
            this.jB_1_2.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_1_2.setName("false");
    }//GEN-LAST:event_jB_1_2ActionPerformed

    private void jB_1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_3ActionPerformed
        disableAllButtons();
        jB_1_3.setBackground(Color.black);
        String[] array = jB_1_3.getName().split("_");
        if(testarJogada(jB_1_3) == false){
            this.jB_1_3.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_1_3.setName("false");
    }//GEN-LAST:event_jB_1_3ActionPerformed

    private void jB_1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_4ActionPerformed
        disableAllButtons();
        jB_1_4.setBackground(Color.black);
        String[] array = jB_1_4.getName().split("_");
        if(testarJogada(jB_1_4) == false){
            this.jB_1_4.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_1_4.setName("false");
    }//GEN-LAST:event_jB_1_4ActionPerformed

    private void jB_2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_0ActionPerformed
        disableAllButtons();
        jB_2_0.setBackground(Color.black);
        String[] array = jB_2_0.getName().split("_");
        if(testarJogada(jB_2_0) == false){
            this.jB_2_0.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_2_0.setName("false");
    }//GEN-LAST:event_jB_2_0ActionPerformed

    private void jB_2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_1ActionPerformed
        disableAllButtons();
        jB_2_1.setBackground(Color.black);
        String[] array = jB_2_1.getName().split("_");
        if(testarJogada(jB_2_1) == false){
            this.jB_2_1.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_2_1.setName("false");
    }//GEN-LAST:event_jB_2_1ActionPerformed

    private void jB_2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_2ActionPerformed
        disableAllButtons();
        jB_2_2.setBackground(Color.black);
        String[] array = jB_2_2.getName().split("_");
        if(testarJogada(jB_2_2) == false){
            this.jB_2_2.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_2_2.setName("false");
    }//GEN-LAST:event_jB_2_2ActionPerformed

    private void jB_2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_3ActionPerformed
        disableAllButtons();
        jB_2_3.setBackground(Color.black);
        String[] array = jB_2_3.getName().split("_");
        if(testarJogada(jB_2_3) == false){
            this.jB_2_3.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_2_3.setName("false");
    }//GEN-LAST:event_jB_2_3ActionPerformed

    private void jB_2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_4ActionPerformed
        disableAllButtons();
        jB_2_4.setBackground(Color.black);
        String[] array = jB_2_4.getName().split("_");
        if(testarJogada(jB_2_4) == false){
            this.jB_2_4.setText("X");   
            try {
                String s = array[1]+"@"+array[2]+"@"+"true"+'\n';
                this.saidaServidor.writeBytes(s);
                esperaVez();
                ////System.out.println("acao botao 00 servidor");
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }else{
            try {
                this.saidaServidor.writeBytes(""+array[1]+"@"+array[2]+"\n");
                ////System.out.println("acao botao 00 servidor");
                esperaVez();
                //disableAllButtons();
            } catch (IOException ex) {
                Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        jB_2_4.setName("false");
    }//GEN-LAST:event_jB_2_4ActionPerformed

    private void jTextIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIPActionPerformed

    private void jB_ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConectarActionPerformed
        
        final String ipHost = jTextIP.getText();
        SwingWorker worker = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    socketCliente = new Socket(ipHost, 6666);
                    entradaServidor = new BufferedReader(new InputStreamReader(socketCliente.getInputStream()));
                    saidaServidor = new DataOutputStream(socketCliente.getOutputStream());
                    //System.out.println("PAROU AQUI CLIENTE");
                    inserirFuro();
                    return null;
                }
            };

            worker.execute();
            jB_Conectar.setEnabled(false);
    }//GEN-LAST:event_jB_ConectarActionPerformed

    public void inserirFuro(){
        Jogo j = this.jogo;
        SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                String stringServidor;
                //mudarCor();                
                disableAllButtons();
                //System.out.println("PAROU AQUI CLIENTE");
                stringServidor = entradaServidor.readLine();
                //System.out.println("Passou do readline no inserir furo");
                if (stringServidor != null){
                    
                    //System.out.println(stringServidor);
                    String[] array = stringServidor.split("@");
                    String button = "jB_"+array[0]+"_"+array[1];
                    jogo.inserirFuro(Integer.parseInt(array[0]),Integer.parseInt(array[1]));
                    //jogo.inserirFuro(0, 0);
                    esperaVez();
                    //mudarCor();
                }// else {
                   // terminarJogo(jogo.getVencedor());
                //}
                return null;
            }
        };
        
        worker.execute();
    }
    
    public void esperaVez(){
        
        SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                String texto, stringServidor;
                int pos;
                //mudarCor();                
                disableAllButtons();
                //System.out.println("Parou no readline no esperaVez");
                stringServidor = entradaServidor.readLine();
                //System.out.println("Passou do readline do esperaVez");
                
                if (stringServidor != null){
                    
                    //System.out.println(stringServidor);
                    String[] array = stringServidor.split("@");
                    //System.out.println("AQUI: "+array.length);
                    boolean acabou = false;
                    if(array.length == 3)
                        acabou = true;
                    String button = "jB_"+array[0]+"_"+array[1];
                    //System.out.println(acabou);
                    marcarBotao(button,acabou);
                    //statusLabel.setText("Sua vez de jogar...");
                    habilitaTabuleiro();
                    //mudarCor();
                }// else {
                   // terminarJogo(jogo.getVencedor());
                //}
                return null;
            }
        };
        
        worker.execute();
    }
    
    public void marcarBotao(String bname, Boolean acabou){
        
        ArrayList<javax.swing.JButton> a = allButton();
        while(a.isEmpty() == false){
            javax.swing.JButton b = a.remove(0);
            if(bname.equals(b.getName())){
                //System.out.println("OI");
                b.setName("false");
                b.setBackground(Color.black);
                //System.out.println(acabou);
                if(acabou == true){
                    b.setText("X");
                    javax.swing.JOptionPane.showMessageDialog(null, "YOOOOU WIN!");
                    disableAllButtons();
                }
                }
        }
    }
    
    public ArrayList allButton(){
        ArrayList<javax.swing.JButton> a = new ArrayList<javax.swing.JButton>();
        a.add(jB_0_0);
        a.add(jB_0_1);
        a.add(jB_0_2);
        a.add(jB_0_3);
        a.add(jB_0_4);
        a.add(jB_1_0);
        a.add(jB_1_1);
        a.add(jB_1_2);
        a.add(jB_1_3);
        a.add(jB_1_4);
        a.add(jB_2_0);
        a.add(jB_2_1);
        a.add(jB_2_2);
        a.add(jB_2_3);
        a.add(jB_2_4);
        return a;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaMultiplayerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaMultiplayerCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_0_0;
    private javax.swing.JButton jB_0_1;
    private javax.swing.JButton jB_0_2;
    private javax.swing.JButton jB_0_3;
    private javax.swing.JButton jB_0_4;
    private javax.swing.JButton jB_1_0;
    private javax.swing.JButton jB_1_1;
    private javax.swing.JButton jB_1_2;
    private javax.swing.JButton jB_1_3;
    private javax.swing.JButton jB_1_4;
    private javax.swing.JButton jB_2_0;
    private javax.swing.JButton jB_2_1;
    private javax.swing.JButton jB_2_2;
    private javax.swing.JButton jB_2_3;
    private javax.swing.JButton jB_2_4;
    private javax.swing.JButton jB_Conectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextIP;
    // End of variables declaration//GEN-END:variables
}
