/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.Jogo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Adelino Neto
 */
public class TelaLocal extends javax.swing.JFrame {
    Jogo jogo;
    /**
     * Creates new form TelaLocal
     */
    public TelaLocal() {
        initComponents();
        jogo = new Jogo(true);
        renomearBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jB_0_0 = new javax.swing.JButton();
        jB_0_1 = new javax.swing.JButton();
        jB_0_2 = new javax.swing.JButton();
        jB_0_3 = new javax.swing.JButton();
        jB_0_4 = new javax.swing.JButton();
        jB_1_0 = new javax.swing.JButton();
        jB_1_1 = new javax.swing.JButton();
        jB_1_2 = new javax.swing.JButton();
        jB_1_3 = new javax.swing.JButton();
        jB_1_4 = new javax.swing.JButton();
        jB_2_0 = new javax.swing.JButton();
        jB_2_1 = new javax.swing.JButton();
        jB_2_2 = new javax.swing.JButton();
        jB_2_3 = new javax.swing.JButton();
        jB_2_4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gif1.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jB_0_0.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_0ActionPerformed(evt);
            }
        });

        jB_0_1.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_1ActionPerformed(evt);
            }
        });

        jB_0_2.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_2ActionPerformed(evt);
            }
        });

        jB_0_3.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_3ActionPerformed(evt);
            }
        });

        jB_0_4.setBackground(new java.awt.Color(153, 51, 0));
        jB_0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0_4ActionPerformed(evt);
            }
        });

        jB_1_0.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_0ActionPerformed(evt);
            }
        });

        jB_1_1.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_1ActionPerformed(evt);
            }
        });

        jB_1_2.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_2ActionPerformed(evt);
            }
        });

        jB_1_3.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_3ActionPerformed(evt);
            }
        });

        jB_1_4.setBackground(new java.awt.Color(153, 51, 0));
        jB_1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1_4ActionPerformed(evt);
            }
        });

        jB_2_0.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_0ActionPerformed(evt);
            }
        });

        jB_2_1.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_1ActionPerformed(evt);
            }
        });

        jB_2_2.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_2ActionPerformed(evt);
            }
        });

        jB_2_3.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_3ActionPerformed(evt);
            }
        });

        jB_2_4.setBackground(new java.awt.Color(153, 51, 0));
        jB_2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jB_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jB_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jB_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean testarJogada(javax.swing.JButton botao){
        String[] array = botao.getName().split("_");
        String nome = array[0]+"_"+array[1]+"_"+array[2];
        int x = Integer.parseInt(array[1]);
        int y = Integer.parseInt(array[2]);
        boolean result = jogo.iniciar(x, y);
        if(result == false){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gif2.gif")));
            botao.setText("X");
            JOptionPane.showMessageDialog(null,"YOU LOSE!");
            return false;
        }
        return true;
    }
    private void jB_0_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_0ActionPerformed
        this.jB_0_0.setEnabled(false);
        if(testarJogada(jB_0_0) == false){
           this.jB_0_0.setText("X");
           disableAllButtons();
        }
    }//GEN-LAST:event_jB_0_0ActionPerformed

    private void jB_0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_1ActionPerformed
        this.jB_0_1.setEnabled(false);
        if(testarJogada(jB_0_1) == false){
           this.jB_0_1.setText("X");
           disableAllButtons();
        }
    }//GEN-LAST:event_jB_0_1ActionPerformed

    private void jB_0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_2ActionPerformed
         this.jB_0_2.setEnabled(false);
        if(testarJogada(jB_0_2) == false){
           this.jB_0_2.setText("X");
           disableAllButtons();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jB_0_2ActionPerformed

    private void jB_0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_3ActionPerformed
         this.jB_0_3.setEnabled(false);
        if(testarJogada(jB_0_3) == false){
           this.jB_0_3.setText("X");
           disableAllButtons();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jB_0_3ActionPerformed

    private void jB_0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0_4ActionPerformed
        this.jB_0_4.setEnabled(false);
        if(testarJogada(jB_0_4) == false){
           this.jB_0_4.setText("X");
           disableAllButtons();
        } // TODO add your handling code here:
    }//GEN-LAST:event_jB_0_4ActionPerformed

    private void jB_1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_0ActionPerformed
         this.jB_1_0.setEnabled(false);
        if(testarJogada(jB_1_0) == false){
           this.jB_1_0.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_1_0ActionPerformed

    private void jB_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_1ActionPerformed
        this.jB_1_1.setEnabled(false);
        if(testarJogada(jB_1_1) == false){
           this.jB_1_1.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_1_1ActionPerformed

    private void jB_1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_2ActionPerformed
        this.jB_1_2.setEnabled(false);
        if(testarJogada(jB_1_2) == false){
           this.jB_1_2.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_1_2ActionPerformed

    private void jB_1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_3ActionPerformed
        this.jB_1_3.setEnabled(false);
        if(testarJogada(jB_1_3) == false){
           this.jB_1_3.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_1_3ActionPerformed

    private void jB_1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1_4ActionPerformed
        this.jB_1_4.setEnabled(false);
        if(testarJogada(jB_1_4) == false){
           this.jB_1_4.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_1_4ActionPerformed

    private void jB_2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_0ActionPerformed
        this.jB_2_0.setEnabled(false);
        if(testarJogada(jB_2_0) == false){
           this.jB_2_0.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_2_0ActionPerformed

    private void jB_2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_1ActionPerformed
        this.jB_2_1.setEnabled(false);
        if(testarJogada(jB_2_1) == false){
           this.jB_2_1.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_2_1ActionPerformed

    private void jB_2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_2ActionPerformed
        this.jB_2_2.setEnabled(false);
        if(testarJogada(jB_2_2) == false){
           this.jB_2_2.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_2_2ActionPerformed

    private void jB_2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_3ActionPerformed
        this.jB_2_3.setEnabled(false);
        if(testarJogada(jB_2_3) == false){
           this.jB_2_3.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_2_3ActionPerformed

    private void jB_2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2_4ActionPerformed
        this.jB_2_4.setEnabled(false);
        if(testarJogada(jB_2_4) == false){
           this.jB_2_4.setText("X");
           disableAllButtons();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jB_2_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_0_0;
    private javax.swing.JButton jB_0_1;
    private javax.swing.JButton jB_0_2;
    private javax.swing.JButton jB_0_3;
    private javax.swing.JButton jB_0_4;
    private javax.swing.JButton jB_1_0;
    private javax.swing.JButton jB_1_1;
    private javax.swing.JButton jB_1_2;
    private javax.swing.JButton jB_1_3;
    private javax.swing.JButton jB_1_4;
    private javax.swing.JButton jB_2_0;
    private javax.swing.JButton jB_2_1;
    private javax.swing.JButton jB_2_2;
    private javax.swing.JButton jB_2_3;
    private javax.swing.JButton jB_2_4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void renomearBotoes() {
        jB_0_0.setName("jB_0_0");
        jB_0_1.setName("jB_0_1");
        jB_0_2.setName("jB_0_2");
        jB_0_3.setName("jB_0_3");
        jB_0_4.setName("jB_0_4");
        jB_1_0.setName("jB_1_0");
        jB_1_1.setName("jB_1_1");
        jB_1_2.setName("jB_1_2");
        jB_1_3.setName("jB_1_3");
        jB_1_4.setName("jB_1_4");
        jB_2_0.setName("jB_2_0");
        jB_2_1.setName("jB_2_1");
        jB_2_2.setName("jB_2_2");
        jB_2_3.setName("jB_2_3");
        jB_2_4.setName("jB_2_4");
    }

    private void disableAllButtons() {
        jB_0_0.setEnabled(false);
        jB_0_1.setEnabled(false);
        jB_0_2.setEnabled(false);
        jB_0_3.setEnabled(false);
        jB_0_4.setEnabled(false);
        jB_1_0.setEnabled(false);
        jB_1_1.setEnabled(false);
        jB_1_2.setEnabled(false);
        jB_1_3.setEnabled(false);
        jB_1_4.setEnabled(false);
        jB_2_0.setEnabled(false);
        jB_2_1.setEnabled(false);
        jB_2_2.setEnabled(false);
        jB_2_3.setEnabled(false);
        jB_2_4.setEnabled(false);
    }
}
